services:
  postgres:
    image: postgres:15.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # copy the sql script to create database
      - ./postgresql/sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      # copy the sql script to create tables
      - ./postgresql/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./postgresql/sql/fill_lookup_tables.sql:/docker-entrypoint-initdb.d/fill_lookup_tables.sql
      - ./postgresql/sql/fill_nonlookup_tables.sql:/docker-entrypoint-initdb.d/fill_nonlookup_tables.sql
      # persist tables in container to local disk
      - ./postgresql/postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  nodejs_app:
    build:
      context: .
      dockerfile: express-typescript/Dockerfile.dev
    hostname: nodejs_app_host
    depends_on:
      - postgres
    # environment keys below are read by application code of container
    # e.g. src/index.ts
    #   console.log('PORT',process.env.PORT)
    #   will show 8081
    environment:
      - NODE_ENV=development
      - PORT=8081
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=me2expenses
      - PGPORT=5432
    volumes:
      - ./express-typescript/src:/usr/src/appparent/app/src
    ports:
      - "3030:8081"
    networks:
      - app_network

  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx/localhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    depends_on:
      - nodejs_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
